CricBuffet/CricBuffet/Areas/Media/Models/MediaDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Areas.Media.Models
{
    public class MediaDetail
    {
        [Key]
        [Column(Order = 1)]
        public int ID { get; set; }

        [ForeignKey("MediaTag")]
        public int MediaTag { get; set; }

        public string MediaTitle { get; set; }

        public string MediaDescription { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime EditDate { get; set; }

        [ForeignKey("Buddy")]
        public int BuddyId { get; set; }

        public int IsActive { get; set; }
    }
}

CricBuffet/CricBuffet/Models/MediaDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Models
{
    public class MediaDetailViewModel
    {
        public int ID { get; set; }

        public int MediaTag { get; set; }

        public string MediaTitle { get; set; }

        public string MediaDescription { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime EditDate { get; set; }

        public int BuddyId { get; set; }

        public int IsActive { get; set; }
    }
}

CricBuffet/CricBuffet/Areas/Admin/Controllers/BuddyController.cs
using Microsoft.AspNetCore.Mvc;
using CricBuffet.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace CricBuffet.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BuddyController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BuddyController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult BuddyList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult BuddyListing()
        {
            List<Buddy> buddys = new List<Buddy>();
            buddys = cricDbContext.Buddy.Where(x => x.IsActive == 0).Select(c => c).ToList();
            return Json(new { data = buddys });
        }

        [HttpGet]
        public IActionResult BuddyCreate(int id = 0)
        {
            return View();
        }

        [HttpGet]
        public IActionResult BuddyView(int? id)
        {
            var buddyList = cricDbContext.Buddy.Where(x => x.ID == id).FirstOrDefault();

            var buddyListView = new BuddyViewModel
            {
                BuddyName = buddyList.BuddyName,
                BuddyPicture = buddyList.BuddyPicture,
                ID = buddyList.ID
            };

            return View(buddyListView);
        }

        [HttpGet]
        public IActionResult BuddyEdit(int? id)
        {
            var buddyList = cricDbContext.Buddy.Where(x => x.ID == id).FirstOrDefault();

            var buddyListEdit = new BuddyViewModel
            {
                BuddyName = buddyList.BuddyName,
                BuddyPicture = buddyList.BuddyPicture,
                ID = buddyList.ID,
            };

            return View(buddyListEdit);
        }

        [HttpPost]
        public IActionResult BuddyEdit(BuddyViewModel buddy)
        {
            //if (ModelState.IsValid)
            //{
            string uniqueFileName = UploadedFile(buddy);
            if (buddy.ID == 0)
            {
                Buddy buddyObj = new Buddy
                {
                    BuddyName = buddy.BuddyName,
                    CreatedDate = DateTime.Now,
                    EditDate = DateTime.Now,
                    BuddyPicture = uniqueFileName,
                    IsActive = 0
                };

                cricDbContext.Add(buddyObj);
                cricDbContext.SaveChanges();
            }
            else
            {
                uniqueFileName = UploadedFile(buddy);
                Buddy buddyObj = cricDbContext.Buddy.Find(buddy.ID);

                buddyObj.BuddyName = buddy.BuddyName;
                buddyObj.EditDate = DateTime.Now;
                buddyObj.BuddyPicture = uniqueFileName;
                cricDbContext.Update(buddyObj);
                cricDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(BuddyList));
            //}
            //return View(buddy);
        }

        private string UploadedFile(BuddyViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfileImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        [HttpPost]
        public IActionResult BuddyDelete(int id)
        {
            Buddy buddy = cricDbContext.Buddy.Find(id);
            buddy.IsActive = 1;
            cricDbContext.Update(buddy);
            cricDbContext.SaveChanges();

            return RedirectToAction(nameof(BuddyList));
        }
    }
}

CricBuffet/CricBuffet/Areas/Media/Controllers/MediaDetailController.cs
using CricBuffet.Areas.Media.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Areas.Media.Controllers
{
    [Area("Media")]
    public class MediaDetailController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public MediaDetailController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MediaDetailList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult MediaDetailListing()
        {
            List<MediaDetail> mediaDetails = new List<MediaDetail>();
            mediaDetails = cricDbContext.MediaDetail.Where(x => x.IsActive == 0).Select(c => c).ToList();
            return Json(new { data = mediaDetails });
        }

        [HttpGet]
        public IActionResult MediaDetailCreate()
        {
            ViewData["BuddyId"] = new SelectList(cricDbContext.Buddy, "ID", "BuddyName");
            ViewData["MediaTag"] = new SelectList(cricDbContext.MediaTag, "ID", "TagName");
            return View();
        }

        [HttpGet]
        public IActionResult MediaDetailEdit(int? id)
        {
            var mediaDetailList = cricDbContext.MediaDetail.Where(x => x.ID == id).FirstOrDefault();
            ViewData["BuddyId"] = new SelectList(cricDbContext.Buddy, "ID", "BuddyName");
            ViewData["MediaTag"] = new SelectList(cricDbContext.MediaTag, "ID", "TagName");
            return View(mediaDetailList);
        }

        [HttpPost]
        public IActionResult MediaDetailEdit(MediaDetail mediaDetail)
        {
            if (mediaDetail.ID == 0)
            {
                MediaDetail mediaDetail1 = new MediaDetail
                {
                    MediaDescription = mediaDetail.MediaDescription,
                    MediaTitle = mediaDetail.MediaTitle,
                    BuddyId = mediaDetail.BuddyId,
                    MediaTag = mediaDetail.MediaTag,
                    IsActive = 0
                };

                cricDbContext.Add(mediaDetail1);
                cricDbContext.SaveChanges();
            }
            else
            {
                MediaDetail mediaDetail1 = cricDbContext.MediaDetail.Find(mediaDetail.ID);
                MediaDetail mediaDetail2 = new MediaDetail
                {
                    MediaDescription = mediaDetail.MediaDescription,
                    MediaTitle = mediaDetail.MediaTitle,
                    BuddyId = mediaDetail.BuddyId,
                    MediaTag = mediaDetail.MediaTag,
                    IsActive = 0
                };

                
               
                cricDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(MediaDetailList));
        }

        [HttpPost]
        public IActionResult MediaDetailDelete(int id)
        {
            MediaDetail mediaDetail = cricDbContext.MediaDetail.Find(id);
            mediaDetail.IsActive = 1;
           
            cricDbContext.SaveChanges();

            return RedirectToAction(nameof(mediaDetail));
        }
    }
}

CricBuffet/CricBuffet/Areas/Media/Views/MediaDetail/MediaDetailCreate.cshtml
@model CricBuffet.Areas.Media.Models.MediaDetail

<link href="~/Scripts/summernote-0.8.18-dist/summernote-bs4.css" rel="stylesheet" />
<link href="~/Scripts/summernote-0.8.18-dist/summernote-lite.css" rel="stylesheet" />
<link href="~/Scripts/summernote-0.8.18-dist/summernote-bs4.css" rel="stylesheet" />

<style>
    .note-editor.note-frame {
        width: 900px
    }
</style>

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Add</span> <span style="color: #1F3BB3">MediaDetail</span>
            </h4>

            @using (Html.BeginForm("MediaDetailEdit", "MediaDetail", FormMethod.Post, new { area = "Media", encType = "multipart/form-data", onSubmit = " return subform(this)", id = "myForm" }))

            {

                @Html.HiddenFor(model => model.ID)

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaTitle, new { @class = "control-label" })
                                    @Html.EditorFor(model => model.MediaTitle, new { htmlAttributes = new { @class = "form-control", @id = "buddyName" } })
                                    @Html.ValidationMessageFor(model => model.MediaTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaDescription, new { @class = "control-label" })
                                    <select asp-for="BuddyId" class="form-control" asp-items="ViewBag.BuddyId">
                                        <option>select buddy</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaTag, new { @class = "control-label" })
                                    <select asp-for="MediaTag" class="form-control" asp-items="ViewBag.MediaTag">
                                        <option>select MediaTag</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaDescription, new { @class = "control-label" })
                                    @Html.TextAreaFor(model => model.MediaDescription, new { htmlAttributes = new { @class = "forming" } })
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group" style="margin-top:50px;margin-left:32px;">
                    <input type="submit" value="Save" class="btn btn-primary" style="padding:3px;font-size:16px" />
                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Buddy" asp-action="BuddyList" tyle="padding:3px;font-size:16px">sBack</a>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote-lite.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote-bs4.js"></script>
<script>

    $('#MediaDescription').summernote({
        height: 300,                 // set editor height
        minHeight: null,             // set minimum height of editor
        maxHeight: null,             // set maximum height of editor
        focus: true

    });
</script>  

CricBuffet/CricBuffet/Areas/Media/Views/MediaDetail/MediaDetailEdit.cshtml
@model CricBuffet.Areas.Media.Models.MediaDetail

<link href="~/Scripts/summernote-0.8.18-dist/summernote-bs4.css" rel="stylesheet" />
<link href="~/Scripts/summernote-0.8.18-dist/summernote-lite.css" rel="stylesheet" />
<link href="~/Scripts/summernote-0.8.18-dist/summernote-bs4.css" rel="stylesheet" />

<style>
    .note-editor.note-frame {
        width: 900px
    }
</style>

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Add</span> <span style="color: #1F3BB3">MediaDetail</span>
            </h4>

            @using (Html.BeginForm("MediaDetailEdit", "MediaDetail", FormMethod.Post, new { area = "Media", encType = "multipart/form-data", onSubmit = " return subform(this)", id = "myForm" }))

            {

                @Html.HiddenFor(model => model.ID)

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaTitle, new { @class = "control-label" })
                                    @Html.EditorFor(model => model.MediaTitle, new { htmlAttributes = new { @class = "form-control", @id = "buddyName" } })
                                    @Html.ValidationMessageFor(model => model.MediaTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.BuddyId, new { @class = "control-label" })
                                    <select asp-for="BuddyId" class="form-control" asp-items="ViewBag.BuddyId">
                                        <option>select buddy</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">

                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaTag, new { @class = "control-label" })
                                    <select asp-for="MediaTag" class="form-control" asp-items="ViewBag.MediaTag">
                                        <option>select MediaTag</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MediaDescription, new { @class = "control-label" })
                                    @Html.TextAreaFor(model => model.MediaDescription, new { htmlAttributes = new { @class = "forming" } })
                                    @Html.ValidationMessageFor(model => model.MediaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group" style="margin-top:50px;margin-left:32px;">
                    <input type="submit" value="Save" class="btn btn-primary" style="padding:3px;font-size:16px" />
                    <input type="submit" value="Back" class="btn btn-danger" style="padding:3px;font-size:16px" />
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote-lite.js"></script>
<script src="~/Scripts/summernote-0.8.18-dist/summernote-bs4.js"></script>
<script>

    $('#MediaDescription').summernote({
        height: 300,                 // set editor height
        minHeight: null,             // set minimum height of editor
        maxHeight: null,             // set maximum height of editor
        focus: true

    });
</script>  

CricBuffet/CricBuffet/Areas/Media/Views/MediaDetail/MediaDetailList.cshtml
<style>
    .dataTable > thead > tr > th[class*="sort"]:before,
    .dataTable > thead > tr > th[class*="sort"]:after {
        content: "" !important;
    }

    .ui-widget-content {
        background: none
    }

    .ui-widget-header {
        background: none
    }

    hr:not([size]) {
        height: 0px;
    }

    #btnu {
        background: #1F3BB3;
        color: white;
        padding: 7px;
        font-size: 12px;
        text-decoration: none;
        border-radius: 25px
    }

        #btnu:hover {
            color: white
        }

    .table th, .table td {
        vertical-align: middle;
        line-height: 1;
        white-space: nowrap;
        padding: 1.125rem 1.375rem;
        font-size: 11px;
        padding: 3px;
        text-align: center;
        font-weight: bold
    }
</style>

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Buddy</span> Place
            </h4>
            <p class="card-description">
                <a class="btn btn-default" id="btnu" asp-area="Media" asp-controller="MediaDetail" asp-action="MediaDetailCreate"><i class="fa fa-plus" style="color:white"></i> Add MediaDetail</a>
            </p>
            <div class="table-responsive">
                <table class="table table-striped" id="buddyTable">
                    <thead>
                        <tr>
                            <th>Media Title </th>
                           
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


@section scripts
        {

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/js/all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/styles/metro/notify-metro.min.css" />

    <script type="text/javascript">
        var submitted, datatable;
        $(document).ready(function () {
            datatable = $('#buddyTable').DataTable({
                "autoWidth": false,
                "ajax": {
                    'url': "/Media/MediaDetail/MediaDetailListing",
                    "type": "GET",
                    "datatype": "json"

                },
                "columns": [
                    { "data": "mediaTitle" },

                    {
                        "data": "id", "render":function (data) {
                            return "<a    href='@Url.Action("MediaDetailEdit", "MediaDetail", new { Area = "Media" })/" + data + "'><i  class='fa fa-pencil'></i> </a><a style='margin-left:20px;color:green' onclick=submission('@Url.Action("BuddyView", "Buddy", new { Area = "Admin" })/" + data + "')><i  class='fa fa-eye'></i></a><a  style='color:red;font-size:15px;margin-left:20px' onclick=DEl(" + data + ") style='margin-left:0px;color:blue;font-size:10px'><i class='fa fa-trash'></i> </a>"
                         },
                        "orderable": false,
                        "width": "150px",
                        "searchable":false
                    }
                ]
            });
        });
         function DEl(id)
        {
            if (confirm("Hey Buddy, are you sure want to delete your MediaDetail!!"))
            {
                $.ajax({
                    type: "Post",
                    url: '@Url.Action("MediaDetailDelete", "MediaDetail", new { Area = "Media" })/' + id,
                    success: function (data) {
                        alert("deleted");
                        datatable.ajax.reload();
                        if (data.success) {

                            $.notify(data.message, {
                                globalPosition: "topright",
                                className: "success"

                            });
                        }
                    }
                });
            }
        }
    </script>

}