CricBuffet/CricBuffet/Areas/Tag/Models/MediaTag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Areas.Tag.Models
{
    public class MediaTag
    {
        [Key]
        public int ID { get; set; }

        public string TagName { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime EditDate { get; set; }

        public int IsActive { get; set; }
    }
}

CricBuffet/CricBuffet/Areas/Admin/Controllers/BuddyController.cs
using Microsoft.AspNetCore.Mvc;
using CricBuffet.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace CricBuffet.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BuddyController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BuddyController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult BuddyList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult BuddyListing()
        {
            List<Buddy> buddys = new List<Buddy>();
            buddys = cricDbContext.Buddy.Where(x => x.IsActive == 0).Select(c => c).ToList();
            return Json(new { data = buddys });
        }

        [HttpGet]
        public IActionResult BuddyCreate(int id = 0)
        {
            return View();
        }

        [HttpGet]
        public IActionResult BuddyView(int? id)
        {
            var buddyList = cricDbContext.Buddy.Where(x => x.ID == id).FirstOrDefault();

            var buddyListView = new BuddyViewModel
            {
                BuddyName = buddyList.BuddyName,
                BuddyPicture = buddyList.BuddyPicture,
                ID = buddyList.ID
            };

            return View(buddyListView);
        }

        [HttpGet]
        public IActionResult BuddyEdit(int? id)
        {
            var buddyList = cricDbContext.Buddy.Where(x => x.ID == id).FirstOrDefault();

            var buddyListEdit = new BuddyViewModel
            {
                BuddyName = buddyList.BuddyName,
                BuddyPicture = buddyList.BuddyPicture,
                ID = buddyList.ID,
            };

            return View(buddyListEdit);
        }

        [HttpPost]
        public IActionResult BuddyEdit(BuddyViewModel buddy)
        {
            //if (ModelState.IsValid)
            //{
            string uniqueFileName = UploadedFile(buddy);
            if (buddy.ID == 0)
            {
                Buddy buddyObj = new Buddy
                {
                    BuddyName = buddy.BuddyName,
                    CreatedDate = DateTime.Now,
                    EditDate = DateTime.Now,
                    BuddyPicture = uniqueFileName,
                    IsActive = 0
                };

                cricDbContext.Add(buddyObj);
                cricDbContext.SaveChanges();
            }
            else
            {
                uniqueFileName = UploadedFile(buddy);
                Buddy buddyObj = cricDbContext.Buddy.Find(buddy.ID);

                buddyObj.BuddyName = buddy.BuddyName;
                buddyObj.EditDate = DateTime.Now;
                buddyObj.BuddyPicture = uniqueFileName;
                cricDbContext.Update(buddyObj);
                cricDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(BuddyList));
            //}
            //return View(buddy);
        }

        private string UploadedFile(BuddyViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfileImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        [HttpPost]
        public IActionResult BuddyDelete(int id)
        {
            Buddy buddy = cricDbContext.Buddy.Find(id);
            buddy.IsActive = 1;
            cricDbContext.Update(buddy);
            cricDbContext.SaveChanges();

            return RedirectToAction(nameof(BuddyList));
        }
    }
}

CricBuffet/CricBuffet/Areas/Menu/Controllers/MediaController.cs
using CricBuffet.Areas.Menu.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Areas.Menu.Controllers
{
    [Area("Menu")]
    public class MediaController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public MediaController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

      
        public IActionResult MediaList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult MenuListing()
        {
            List<MediaMenu> menulist = new List<MediaMenu>();
            menulist = cricDbContext.MediaMenu.Where(x => x.IsActive == 0).Select(c => c).ToList();
            return Json(new { data = menulist });
        }

        [HttpGet]
        public IActionResult MenuCreate(int id = 0)
        {
            return View();
        }

        [HttpGet]
        public IActionResult MenuView(int? id)
        {
            var menuList = cricDbContext.MediaMenu.Where(x => x.Id == id).FirstOrDefault();

            return View(menuList);
        }

        [HttpGet]
        public IActionResult MenuEdit(int? id)
        {
            var menuList = cricDbContext.MediaMenu.Where(x => x.Id == id).FirstOrDefault();

            return View(menuList);
        }

        [HttpPost]
        public IActionResult MenuEdit(MediaMenu mediaMenu)
        {
            //if (ModelState.IsValid)
            //{
            if (mediaMenu.Id == 0)
            {
                MediaMenu menuObj = new MediaMenu
                {
                    MediaMenuName = mediaMenu.MediaMenuName,
                    CreatedDate = DateTime.Now,
                    EditDate = DateTime.Now,
                    IsActive = 0
                };

                cricDbContext.Add(menuObj);
                cricDbContext.SaveChanges();
            }
            else
            {
                MediaMenu menuObj = cricDbContext.MediaMenu.Find(mediaMenu.Id);

                menuObj.MediaMenuName = mediaMenu.MediaMenuName;
                menuObj.EditDate = DateTime.Now;
                cricDbContext.Update(menuObj);
                cricDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(MediaList));
        }

        [HttpPost]
        public IActionResult MenuDelete(int id)
        {
            MediaMenu menu = cricDbContext.MediaMenu.Find(id);
            menu.IsActive = 1;
            cricDbContext.Update(menu);
            cricDbContext.SaveChanges();

            return RedirectToAction(nameof(MediaList));
        }
    }
}

CricBuffet/CricBuffet/Areas/Tag/Controllers/MediaTagController.cs
using CricBuffet.Areas.Tag.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Areas.Tag.Controllers
{
    [Area("Tag")]
    public class MediaTagController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public MediaTagController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MediaTagList()
        {
            return View();
        }

        [HttpGet]
        public JsonResult MediaTagListing()
        {
            List<MediaTag> menulist = new List<MediaTag>();
            menulist = cricDbContext.MediaTag.Where(x => x.IsActive == 0).Select(c => c).ToList();
            return Json(new { data = menulist });
        }

        [HttpGet]
        public IActionResult MediaTagCreate(int id = 0)
        {
            return View();
        }

        [HttpGet]
        public IActionResult MediaTagEdit(int? id)
        {
            var menuList = cricDbContext.MediaTag.Where(x => x.ID == id).FirstOrDefault();

            return View(menuList);
        }

        [HttpPost]
        public IActionResult MediaTagEdit(MediaTag mediaTag)
        {
            //if (ModelState.IsValid)
            //{
            if (mediaTag.ID == 0)
            {
                MediaTag mediaTag1 = new MediaTag
                {
                    TagName = mediaTag.TagName,
                    CreatedDate = DateTime.Now,
                    EditDate = DateTime.Now,
                    IsActive = 0
                };

                cricDbContext.Add(mediaTag1);
                cricDbContext.SaveChanges();
            }
            else
            {
                MediaTag mediaTag1 = cricDbContext.MediaTag.Find(mediaTag.ID);

                mediaTag1.TagName = mediaTag1.TagName;
                mediaTag1.EditDate = DateTime.Now;
                cricDbContext.Update(mediaTag1);
                cricDbContext.SaveChanges();
            }

            return RedirectToAction(nameof(MediaTagList));
        }

        [HttpPost]
        public IActionResult MediaTagDelete(int id)
        {
            MediaTag mediaTag = cricDbContext.MediaTag.Find(id);
            mediaTag.IsActive = 1;
            cricDbContext.Update(mediaTag);
            cricDbContext.SaveChanges();

            return RedirectToAction(nameof(MediaTagList));
        }
    }
}

CricBuffet/CricBuffet/Areas/Tag/Views/MediaTag/MediaTagCreate.cshtml
@model CricBuffet.Areas.Tag.Models.MediaTag

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Add</span> <span style="color: #1F3BB3">Menu</span>
            </h4>

            @using (Html.BeginForm("MediaTagEdit", "MediaTag", FormMethod.Post, new { area = "Tag", encType = "multipart/form-data", onSubmit = " return subform(this)" }))

            {

                @Html.HiddenFor(model => model.ID)

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TagName, new { @class = "control-label" })
                                    @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control", @id = "menuName" } })
                                    @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group" style="margin-top:50px;margin-left:12px;">
                    <input type="submit" value="Save" class="btn btn-primary" style="padding:3px;font-size:16px" />
                    <a class="btn btn-danger" href='@Url.Action("MediaTagList", "MediaTag", new { Area = "Tag" })' style="padding:5px">Back</a>
                </div>
            }
        </div>
    </div>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

CricBuffet/CricBuffet/Areas/Tag/Views/MediaTag/MediaTagEdit.cshtml
@model CricBuffet.Areas.Tag.Models.MediaTag

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Add</span> <span style="color: #1F3BB3">Menu</span>
            </h4>

            @using (Html.BeginForm("MediaTagEdit", "MediaTag", FormMethod.Post, new { area = "Tag", encType = "multipart/form-data", onSubmit = " return subform(this)" }))

            {

                @Html.HiddenFor(model => model.ID)

                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TagName, new { @class = "control-label" })
                                    @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control", @id = "menuName" } })
                                    @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group" style="margin-top:50px;margin-left:12px;">
                    <input type="submit" value="Save" class="btn btn-primary" style="padding:3px;font-size:16px" />
                    <a class="btn btn-danger" href='@Url.Action("MediaTagList", "MediaTag", new { Area = "Tag" })' style="padding:5px">Back</a>
                </div>
            }
        </div>
    </div>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

CricBuffet/CricBuffet/Areas/Tag/Views/MediaTag/MediaTagList.cshtml
<style>
    .dataTable > thead > tr > th[class*="sort"]:before,
    .dataTable > thead > tr > th[class*="sort"]:after {
        content: "" !important;
    }

    .ui-widget-content {
        background: none
    }

    .ui-widget-header {
        background: none
    }

    hr:not([size]) {
        height: 0px;
    }

    #btnu {
        background: #1F3BB3;
        color: white;
        padding: 7px;
        font-size: 12px;
        text-decoration: none;
        border-radius: 25px
    }

        #btnu:hover {
            color: white
        }

    .table th, .table td {
        vertical-align: middle;
        line-height: 1;
        white-space: nowrap;
        padding: 1.125rem 1.375rem;
        font-size: 11px;
        padding: 14px;
        text-align: center;
        font-weight: bold
    }
</style>

<div class="col-lg-12 grid-margin stretch-card" style="margin-top:-36px">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
                <span style="color: #76bf70">Tag</span> List
            </h4>
            <p class="card-description">
                <a class="btn btn-default" id="btnu" href='@Url.Action("MeDiaTagCreate", "MediaTag", new { Area = "Tag" })'><i class="fa fa-plus" style="color:white"></i> Add Tag</a>
            </p>
            <div class="table-responsive">
                <table class="table table-striped" id="menuTable">
                    <thead>
                        <tr>
                            <th>Tag Name</th>
                            <th>Created Date</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@*<div class="container">

        <p style="margin-top: -90px; color: #1F3BB3; font-size: 20px; font-weight: bold;"><span style="color: #76bf70">Buddy</span> Place</p>
        <br />
        <a class="btn btn-default" id="btnu" onclick="submission('@Url.Action("BuddyCreate", "Buddy", new { Area = "Admin" })')"><i class="fa fa-plus" style="color:white"></i> Add Buddy</a>
        <div style="margin-top:22px">
            <table id="buddyTable1" class="table table-striped">
                <thead>
                    <tr>
                        <th>Buddy </th>
                        <th>Buddy Name</th>
                        <th>Created Date</th>
                        <th>Edit Date</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>*@

@section scripts
        {

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/js/all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/styles/metro/notify-metro.min.css" />

    <script type="text/javascript">
        var submitted, datatable;
        $(document).ready(function () {
            datatable = $('#menuTable').DataTable({
                "autoWidth": false,
                "ajax": {
                    'url': "/Tag/MediaTag/MediaTagListing",
                    "type": "GET",
                    "datatype": "json"

                },
                "columns": [

                    { "data": "tagName" },

                    { "data": "createdDate" },
                    {
                        "data": "id", "render":function (data) {
                            return "<a   href='@Url.Action("MediaTagEdit", "MediaTag", new { Area = "Tag" })/" + data + "'><i  class='fa fa-pencil'></i> </a><a style='margin-left:20px;color:green' onclick=submission('@Url.Action("MenuView", "Media", new { Area = "Menu" })/" + data + "')><i  class='fa fa-eye'></i></a><a  style='color:red;font-size:15px;margin-left:20px' onclick=DEl(" + data + ") style='margin-left:0px;color:blue;font-size:10px'><i class='fa fa-trash'></i> </a>"
                         },
                        "orderable": false,
                        "width": "150px",
                        "searchable":false
                    }
                ]
            });
        });

         function DEl(id)
        {
            if (confirm("Hey Buddy, are you sure want to delete your buddy!!"))
            {
                $.ajax({
                    type: "Post",
                    url: '@Url.Action("MediaTagDelete", "MediaTag", new { Area = "Tag" })/' + id,
                    success: function (data) {
                        alert("deleted");
                        datatable.ajax.reload();
                        if (data.success) {

                            $.notify(data.message, {
                                globalPosition: "topright",
                                className: "success"

                            });
                        }
                    }
                });
            }
        }
    </script>

}