CricBuffet/CricBuffet/Controllers/CricBuffetController.cs
using CricBuffet.Areas.Media.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CricBuffet.Controllers
{
    public class CricBuffetController : Controller
    {
        private readonly CricDbContext cricDbContext;
        private readonly IWebHostEnvironment webHostEnvironment;

        public CricBuffetController(CricDbContext cricDbContexts, IWebHostEnvironment hostEnvironment)
        {
            cricDbContext = cricDbContexts;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult Home()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetFirstSlot()
        {
            try
            {
                var mediaDetailList = cricDbContext.MediaDetail.Where(x => x.IsActive == 0).First();

                return Json(mediaDetailList);
            }
            catch (Exception ex)
            {
                return Json(data: ex);
            }
        }

        [HttpGet]
        public ContentResult GetBuddyName(int BuddyId)
        {
            var buddyName = cricDbContext.Buddy.Where(x => x.ID == BuddyId).Select(x => x.BuddyName).FirstOrDefault();
            return Content(buddyName);
        }

        [HttpGet]
        public ContentResult GetMediaTagName(int TagId)
        {
            var mediaTagName = cricDbContext.MediaTag.Where(x => x.ID == TagId).Select(x => x.TagName).FirstOrDefault();
            return Content(mediaTagName);
        }

        public IActionResult GetMediaDetailView(MediaDetail mediaDetail)
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetMediaDetailViewDetails(MediaDetail mediaDetail)
        {
            int MediaDetailId;
            MediaDetailId = int.Parse(TempData["ID"].ToString());
            var mediaDetails = cricDbContext.MediaDetail.Where(x => x.ID == MediaDetailId).FirstOrDefault();
            return Json(mediaDetails);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

CricBuffet/CricBuffet/Views/CricBuffet/Home.cshtml
@{
    Layout = "~/Views/Shared/CricBuffetLayout.cshtml";
}

<section class="section first-section">
    <div class="container-fluid">
        <div class="masonry-blog clearfix">
            <div class="first-slot">
                <div class="masonry-box post-media">
                    <img src="upload/tech_01.jpg" alt="" class="img-fluid">
                    <div class="shadoweffect">
                        <div class="shadow-desc">
                            <div class="blog-meta" id="firstslot">
                            </div><!-- end meta -->
                        </div><!-- end shadow-desc -->
                    </div><!-- end shadow -->
                </div><!-- end post-media -->
            </div><!-- end first-side -->

            <div class="second-slot">
                <div class="masonry-box post-media">
                    <img src="upload/tech_02.jpg" alt="" class="img-fluid">
                    <div class="shadoweffect">
                        <div class="shadow-desc">
                            <div class="blog-meta" id="secondslot">
                                <span class="bg-orange"><a href="tech-category-01.html" title="">Gadgets</a></span>
                                <h4><a href="tech-single.html" title="">Do not make mistakes when choosing web hosting</a></h4>
                                <small><a href="tech-single.html" title="">03 July, 2017</a></small>
                                <small><a href="tech-author.html" title="">by Jessica</a></small>
                            </div><!-- end meta -->
                        </div><!-- end shadow-desc -->
                    </div><!-- end shadow -->
                </div><!-- end post-media -->
            </div><!-- end second-side -->

            <div class="last-slot">
                <div class="masonry-box post-media">
                    <img src="upload/tech_03.jpg" alt="" class="img-fluid">
                    <div class="shadoweffect">
                        <div class="shadow-desc">
                            <div class="blog-meta" id="thirdslot">
                                <span class="bg-orange"><a href="tech-category-01.html" title="">Technology</a></span>
                                <h4><a href="tech-single.html" title="">The most reliable Galaxy Note 8 images leaked</a></h4>
                                <small><a href="tech-single.html" title="">01 July, 2017</a></small>
                                <small><a href="tech-author.html" title="">by Jessica</a></small>
                            </div><!-- end meta -->
                        </div><!-- end shadow-desc -->
                    </div><!-- end shadow -->
                </div><!-- end post-media -->
            </div><!-- end second-side -->
        </div><!-- end masonry -->
    </div>
</section>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {

        $.ajax({
            type: "GET",
            "url": "/CricBuffet/GetFirstSlot",
            success: function (data) {

                alert(JSON.stringify(data));

                var BuddyName = GetBuddyName(data.buddyId);

                var MediaTagName = GetMediaTagName(data.mediaTag);

                var html = '<span class="bg-orange"><a href="tech-category-01.html" title="">' + MediaTagName + '</a></span><h4> <a href= "/CricBuffet/GetMediaDetailView/'+data+'" title="">' + data.mediaTitle + '</a></h4> <small><a href="tech-single.html" title="">' + data.createdDate + '</a></small><small><a href="tech-author.html" title="">' + BuddyName + '</a></small>';
                    $("#firstslot").append(html);

            }
        });

        function GetBuddyName(buddyId) {
            var returnValue;
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetBuddyName", "CricBuffet")?BuddyId=' + buddyId,
                async: false,
                success: function (data) {
                    returnValue = data;
                }
            });
            return returnValue;
        }

        function GetMediaTagName(mediaTagId) {
            var returnTagName;
             $.ajax({
                 type: "GET",
                 url: '@Url.Action("GetMediaTagName", "CricBuffet")?TagId=' + mediaTagId,
                  async: false,
                 success: function (data) {
                     returnTagName = data;
                }
             });
            return returnTagName;
        }

    })
</script>